export const STOCKS = [
    { id: 'tcs', name: 'TCS', price: 3850.45, dailyChange: 1.2, risk: 'Safe', recommendation: 'Buy', type: 'long', growthLabel: 'Moderate', rating: 5, description: 'Tata Consultancy Services is a strong, stable IT giant offering steady, low-risk returns.', riskExplanation: 'Extremely well-capitalized with consistent free cash flows, avoiding major tech volatility.', expectedGrowth: '10-12% annually + steady dividend.' },
    { id: 'reliance', name: 'Reliance', price: 2950.10, dailyChange: -0.4, risk: 'Moderate', recommendation: 'Hold', type: 'long', growthLabel: 'High', rating: 4, description: 'India\'s largest conglomerate with dominant positions in telecom, retail, and energy.', riskExplanation: 'Subject to regulatory and capital-intense industry cycles, but offset by massive market dominance.', expectedGrowth: '15-18% annually.' },
    { id: 'infosys', name: 'Infosys', price: 1540.25, dailyChange: 2.5, risk: 'Moderate', recommendation: 'Buy', type: 'short', growthLabel: 'Moderate', rating: 4, description: 'Global leader in next-gen digital services. Recently showed positive breakout.', riskExplanation: 'Global IT budget tightening could impact margins, but technicals are bullish.', expectedGrowth: 'Short-term upside target of ~8%.' },
    { id: 'hdfc', name: 'HDFC Bank', price: 1420.75, dailyChange: 0.8, risk: 'Safe', recommendation: 'Buy', type: 'long', growthLabel: 'Moderate', rating: 5, description: 'India\'s largest private sector bank. Excellent fundamentals.', riskExplanation: 'Asset quality is best-in-class, representing the safest banking bet.', expectedGrowth: '14-16% compounding over the long horizon.' },
    { id: 'icici', name: 'ICICI Bank', price: 1080.30, dailyChange: 1.5, risk: 'Moderate', recommendation: 'Buy', type: 'short', growthLabel: 'High', rating: 4, description: 'Strong quarterly results and improving asset quality make this a hot pick.', riskExplanation: 'Higher beta relative to the sector, making it slightly more volatile.', expectedGrowth: 'Immediate 10% upside potential limit.' },
    { id: 'zomato', name: 'Zomato', price: 165.50, dailyChange: -3.2, risk: 'Aggressive', recommendation: 'Hold', type: 'short', growthLabel: 'High', rating: 3, description: 'High volatility food-delivery tech stock.', riskExplanation: 'Highly sensitive to consumer spending and competition.', expectedGrowth: 'Explosive multi-bagger potential if margins hold.' },
    { id: 'itc', name: 'ITC Ltd.', price: 450.80, dailyChange: 0.1, risk: 'Safe', recommendation: 'Buy', type: 'long', growthLabel: 'Moderate', rating: 5, description: 'A classic defensive stock with excellent dividend yield.', riskExplanation: 'Virtually no debt and highly defensive FMCG play protects against downside.', expectedGrowth: '7-9% capital appreciation plus a 4% dividend yield.' },
    
    // NEW STOCKS ADDED TO REACH 20+
    { id: 'tamo', name: 'Tata Motors', price: 980.50, dailyChange: 3.4, risk: 'Aggressive', recommendation: 'Buy', type: 'short', growthLabel: 'High', rating: 4, description: 'Strong EV sales momentum making it a solid short-to-medium play.', riskExplanation: 'Auto sector cycles can turn aggressively on supply chain snags.', expectedGrowth: '15-20% short-term upside on EV margins.' },
    { id: 'sbi', name: 'State Bank of India', price: 740.20, dailyChange: -1.2, risk: 'Moderate', recommendation: 'Buy', type: 'long', growthLabel: 'Moderate', rating: 4, description: 'India\'s largest public sector bank with massive rural reach.', riskExplanation: 'PSU banking risks remain, but asset quality has cleaned up massively.', expectedGrowth: '12% long-term compounding.' },
    { id: 'wipro', name: 'Wipro', price: 480.15, dailyChange: 0.5, risk: 'Moderate', recommendation: 'Hold', type: 'short', growthLabel: 'Moderate', rating: 3, description: 'Turnaround story in the IT sector under new leadership.', riskExplanation: 'Turnarounds take time and face execution risks in tough macro environments.', expectedGrowth: '8-10% sideways growth until breakout.' },
    { id: 'lt', name: 'Larsen & Toubro', price: 3450.00, dailyChange: 2.1, risk: 'Safe', recommendation: 'Buy', type: 'long', growthLabel: 'High', rating: 5, description: 'Proxy to India\'s infrastructure capital expenditure cycle.', riskExplanation: 'Very strong order book minimizes downside, though project delays are systemic risks.', expectedGrowth: '15-18% steady ROI over 5 years.' },
    { id: 'ongc', name: 'ONGC', price: 275.40, dailyChange: -0.8, risk: 'Safe', recommendation: 'Hold', type: 'long', growthLabel: 'Stable', rating: 3, description: 'High dividend yield PSU oil explorer.', riskExplanation: 'Highly dependent on crude pricing policies globally.', expectedGrowth: 'Minimal capital growth but 6%+ dividend.' },
    { id: 'ntpc', name: 'NTPC', price: 340.90, dailyChange: 1.1, risk: 'Safe', recommendation: 'Buy', type: 'long', growthLabel: 'Moderate', rating: 4, description: 'Power giant transitioning heavily into renewable energy.', riskExplanation: 'Regulated returns ensure safety, transition costs present mild margin pressure.', expectedGrowth: '12-14% total return including strong dividends.' },
    { id: 'mm', name: 'M&M', price: 1950.60, dailyChange: 4.2, risk: 'Aggressive', recommendation: 'Buy', type: 'short', growthLabel: 'High', rating: 4, description: 'Dominant SUV and tractor portfolio firing on all cylinders.', riskExplanation: 'Rural stress can impact tractor sales, but SUV demand is inelastic currently.', expectedGrowth: '20% upside on upcoming model launches.' },
    { id: 'bajfinance', name: 'Bajaj Finance', price: 6850.00, dailyChange: -2.5, risk: 'Aggressive', recommendation: 'Buy', type: 'long', growthLabel: 'High', rating: 5, description: 'Unmatched consumer lending growth and ROE.', riskExplanation: 'High valuation multiple means severe drawdowns during bad news cycles.', expectedGrowth: '20-25% CAGR historically, expected to continue at 18%.' },
    { id: 'hul', name: 'HUL', price: 2280.45, dailyChange: 0.2, risk: 'Safe', recommendation: 'Hold', type: 'long', growthLabel: 'Stable', rating: 4, description: 'FMCG bellwether with defensive characteristics.', riskExplanation: 'Rural inflation eating into volume growth temporarily.', expectedGrowth: 'Safe 8-10% growth during market downturns.' },
    { id: 'asianpaints', name: 'Asian Paints', price: 2840.10, dailyChange: -1.5, risk: 'Moderate', recommendation: 'Buy', type: 'long', growthLabel: 'High', rating: 5, description: 'Unchallenged pricing power in the decorative paints segment.', riskExplanation: 'Crude oil spikes directly impact their raw material margins.', expectedGrowth: '15% compounding growth over decade.' },
    { id: 'sunpharma', name: 'Sun Pharma', price: 1560.80, dailyChange: 1.8, risk: 'Moderate', recommendation: 'Buy', type: 'short', growthLabel: 'Moderate', rating: 4, description: 'Strong specialty portfolio gaining traction in the US.', riskExplanation: 'FDA regulatory hurdles are a constant wildcard in pharma.', expectedGrowth: '12-15% short-term FDA clearance bounce.' },
    { id: 'titan', name: 'Titan', price: 3670.20, dailyChange: 0.9, risk: 'Safe', recommendation: 'Hold', type: 'long', growthLabel: 'High', rating: 5, description: 'Jewelry market share gainer with massive pricing power.', riskExplanation: 'Valuation is always rich, making timing of entry critical.', expectedGrowth: '18-20% long-term structural compounding.' },
    { id: 'ultratech', name: 'UltraTech Cement', price: 9840.50, dailyChange: 2.3, risk: 'Moderate', recommendation: 'Buy', type: 'short', growthLabel: 'High', rating: 4, description: 'Leader in cement capacity preparing for infra push.', riskExplanation: 'Power and fuel costs largely dictate quarterly performance.', expectedGrowth: '15% cyclical upside.' },
    { id: 'jsw', name: 'JSW Steel', price: 820.40, dailyChange: -3.1, risk: 'Aggressive', recommendation: 'Avoid', type: 'short', growthLabel: 'Moderate', rating: 3, description: 'Highly cyclical steel producer currently facing pricing headwinds.', riskExplanation: 'Global steel dumping from China crushing margins.', expectedGrowth: 'Negative short-term outlook.' },
    { id: 'airtel', name: 'Bharti Airtel', price: 1240.60, dailyChange: 1.0, risk: 'Moderate', recommendation: 'Buy', type: 'long', growthLabel: 'High', rating: 5, description: 'Telecom duopoly beneficiary continuously raising ARPU.', riskExplanation: 'Capex intensive 5G rollouts limit massive free cash flow temporarily.', expectedGrowth: '15-18% structural growth on tariff hikes.' },
    { id: 'hcl', name: 'HCL Tech', price: 1610.20, dailyChange: 0.4, risk: 'Safe', recommendation: 'Hold', type: 'long', growthLabel: 'Moderate', rating: 4, description: 'Excellent software and infrastructure managed services portfolio.', riskExplanation: 'Slightly lower margin profile than TCS.', expectedGrowth: '10-12% reliable appreciation.' },
    { id: 'adani', name: 'Adani Ent', price: 3140.80, dailyChange: 5.6, risk: 'Aggressive', recommendation: 'Buy', type: 'short', growthLabel: 'High', rating: 2, description: 'High-beta infrastructure conglomerate with massive ongoing projects.', riskExplanation: 'Extremely volatile based on newsflow and high debt levels.', expectedGrowth: 'High-risk 30% upside or downside.' },
    { id: 'powergrid', name: 'Power Grid', price: 290.15, dailyChange: 0.5, risk: 'Safe', recommendation: 'Buy', type: 'long', growthLabel: 'Stable', rating: 4, description: 'Monopoly in power transmission with massive dividends.', riskExplanation: 'Almost zero competitive risk, purely regulatory return risk.', expectedGrowth: '5% growth + 6% dividend = 11% safe returns.' }
];
